In [2]:
import pandas as pd
import numpy as np

In [3]:
%pwd

'/home/shared/code'

In [3]:
delay_features = [
    'DayOfWeek',
    'FlightDate',
    'IATA_CODE_Reporting_Airline',
    'Tail_Number',
    'Flight_Number_Reporting_Airline',
    'OriginAirportID',
    'Origin',
    'OriginState',
    'DestAirportID',
    'Dest',
    'DestState',
    'CRSDepTime',
    'DepTime',
    'DepDelayMinutes',
    'CRSArrTime',
    'ArrTime',
    'ArrDelayMinutes',
    'Cancelled',
    'CancellationCode',
    'Diverted',
    'CarrierDelay',
    'WeatherDelay',
    'NASDelay',
    'SecurityDelay',
    'LateAircraftDelay'
]

dtypes = {
    'DayOfWeek':                       int,
    'FlightDate':                      'string',
    'IATA_CODE_Reporting_Airline':     'string',
    'Tail_Number':                     'string',
    'Flight_Number_Reporting_Airline': int,
    'OriginAirportID':                 int,
    'Origin':                          'string',
    'OriginState':                     'string',
    'DestAirportID':                   int,
    'Dest':                            'string',
    'DestState':                       'string',
    'CRSDepTime':                      int,
    'DepTime':                         np.float64,
    'DepDelayMinutes':                 np.float64,
    'CRSArrTime':                      int,
    'ArrTime':                         np.float64,
    'ArrDelayMinutes':                 np.float64,
    'Cancelled':                       int,
    'CancellationCode':                'string',
    'Diverted':                        int,
    'CarrierDelay':                    np.float64,
    'WeatherDelay':                    np.float64,
    'NASDelay':                        np.float64,
    'SecurityDelay':                   np.float64,
    'LateAircraftDelay':               np.float64
}

In [4]:
add_header = True
chunksize = 10**5

for chunk in pd.read_csv('data/airline-performance/aperf-2022.csv', chunksize=chunksize, usecols=delay_features, dtype=dtypes):
    chunk.to_csv('data/airline-performance/aperf-2022-dropped.csv', mode='a', index=False, header=add_header)
    if add_header:
        # The header should not be printed more than one
        add_header = False

In [5]:
df = pd.read_csv('data/airline-performance/aperf-2022-dropped.csv', dtype=dtypes)
df

,DayOfWeek,FlightDate,IATA_CODE_Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginAirportID,Origin,OriginState,DestAirportID,Dest,...,ArrTime,ArrDelayMinutes,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,5,2022-01-14,YX,N119HQ,4879,11066,CMH,OH,11278,DCA,...,1356.0,4.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
1,6,2022-01-15,YX,N122HQ,4879,11066,CMH,OH,11278,DCA,...,1328.0,0.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
2,7,2022-01-16,YX,N412YX,4879,11066,CMH,OH,11278,DCA,...,1339.0,0.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
3,1,2022-01-17,YX,N405YX,4879,11066,CMH,OH,11278,DCA,...,1401.0,9.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
4,2,2022-01-18,YX,N420YX,4879,11066,CMH,OH,11278,DCA,...,1323.0,0.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6729120,3,2022-12-21,NK,N623NK,913,13198,MCI,MO,12892,LAX,...,1742.0,0.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
6729121,4,2022-12-22,NK,N623NK,913,13198,MCI,MO,12892,LAX,...,1750.0,0.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
6729122,5,2022-12-23,NK,N692NK,913,13198,MCI,MO,12892,LAX,...,1734.0,0.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
6729123,6,2022-12-24,NK,N622NK,913,13198,MCI,MO,12892,LAX,...,1722.0,0.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
6729124,7,2022-12-25,NK,N622NK,913,13198,MCI,MO,12892,LAX,...,NaN,NaN,1,B,0,NaN,NaN,NaN,NaN,NaN

In [6]:
df = df.loc[(df['DepDelayMinutes'] > 0.0) | (df['ArrDelayMinutes'] > 0.0)]
df

,DayOfWeek,FlightDate,IATA_CODE_Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginAirportID,Origin,OriginState,DestAirportID,Dest,...,ArrTime,ArrDelayMinutes,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,5,2022-01-14,YX,N119HQ,4879,11066,CMH,OH,11278,DCA,...,1356.0,4.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
3,1,2022-01-17,YX,N405YX,4879,11066,CMH,OH,11278,DCA,...,1401.0,9.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
6,4,2022-01-20,YX,N116HQ,4879,11066,CMH,OH,11278,DCA,...,1358.0,6.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
7,5,2022-01-21,YX,N419YX,4879,11066,CMH,OH,11278,DCA,...,1408.0,16.0,0,<NA>,0,0.0,0.0,16.0,0.0,0.0
10,1,2022-01-24,YX,N128HQ,4879,11066,CMH,OH,11278,DCA,...,1405.0,13.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6729106,3,2022-12-07,NK,N698NK,913,13198,MCI,MO,12892,LAX,...,1810.0,14.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
6729110,7,2022-12-11,NK,N649NK,913,13198,MCI,MO,12892,LAX,...,1836.0,40.0,0,<NA>,0,16.0,0.0,24.0,0.0,0.0
6729118,1,2022-12-19,NK,N611NK,913,13198,MCI,MO,12892,LAX,...,1831.0,35.0,0,<NA>,0,0.0,0.0,2.0,0.0,33.0
6729119,2,2022-12-20,NK,N614NK,913,13198,MCI,MO,12892,LAX,...,1750.0,0.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN
6729122,5,2022-12-23,NK,N692NK,913,13198,MCI,MO,12892,LAX,...,1734.0,0.0,0,<NA>,0,NaN,NaN,NaN,NaN,NaN

In [7]:
bird_df = pd.read_csv('data/bird-strike/bird-strike.csv')
bird_df

/tmp/ipykernel_5972/1820331372.py:1: DtypeWarning: Columns (17,20) have mixed types. Specify dtype option on import or set low_memory=False.
  bird_df = pd.read_csv('data/bird-strike/bird-strike.csv')

,INDEX_NR,INCIDENT_DATE,INCIDENT_MONTH,INCIDENT_YEAR,TIME,TIME_OF_DAY,AIRPORT_ID,AIRPORT,LATITUDE,LONGITUDE,...,NR_INJURIES,NR_FATALITIES,COMMENTS,REPORTED_NAME,REPORTED_TITLE,SOURCE,PERSON,LUPDATE,TRANSFER,DISTANCE
0,608242,06/22/96 00:00:00,6,1996,NaN,NaN,KSMF,SACRAMENTO INTL,38.69542,-121.59077,...,NaN,NaN,/Legacy Record=100001/,REDACTED,REDACTED,Air Transport Report,Air Transport Operations,12/20/07 00:00:00,0,0.0
1,608243,06/26/96 00:00:00,6,1996,NaN,NaN,KDEN,DENVER INTL AIRPORT,39.85841,-104.66700,...,NaN,NaN,/Legacy Record=100002/,REDACTED,REDACTED,Air Transport Report,Air Transport Operations,12/20/07 00:00:00,0,0.0
2,608244,07/01/96 00:00:00,7,1996,NaN,NaN,KOMA,EPPLEY AIRFIELD,41.30252,-95.89417,...,NaN,NaN,/Legacy Record=100003/,REDACTED,REDACTED,Air Transport Report,Air Transport Operations,12/20/07 00:00:00,0,0.0
3,608245,07/01/96 00:00:00,7,1996,NaN,NaN,KIAD,WASHINGTON DULLES INTL ARPT,38.94453,-77.45581,...,NaN,NaN,/Legacy Record=100004/,REDACTED,REDACTED,Air Transport Report,Air Transport Operations,12/20/07 00:00:00,0,NaN
4,608246,07/01/96 00:00:00,7,1996,NaN,NaN,KLGA,LA GUARDIA ARPT,40.77724,-73.87261,...,NaN,NaN,/Legacy Record=100005/,REDACTED,REDACTED,Air Transport Report,Air Transport Operations,12/20/07 00:00:00,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288598,1471167,08/25/23 00:00:00,8,2023,01:22,NaN,KDEN,DENVER INTL AIRPORT,39.85841,-104.66700,...,NaN,NaN,NaN,REDACTED,REDACTED,FAA Form 5200-7-E,Carcass Found,11/09/23 00:00:00,0,0.0
288599,1471168,08/25/23 00:00:00,8,2023,09:20,NaN,KSLC,SALT LAKE CITY INTL,40.78839,-111.97777,...,NaN,NaN,NaN,REDACTED,REDACTED,FAA Form 5200-7-E,Carcass Found,11/09/23 00:00:00,0,0.0
288600,1471170,08/25/23 00:00:00,8,2023,23:45,Night,KBWI,BALTIMORE/WASH INTL THURGOOD MARSHAL ARPT,39.17540,-76.66820,...,NaN,NaN,NaN,REDACTED,REDACTED,FAA Form 5200-7-E,Tower,11/09/23 00:00:00,0,NaN
288601,1471175,08/25/23 00:00:00,8,2023,12:05,Night,KMEM,MEMPHIS INTL,35.04242,-89.97667,...,NaN,NaN,NaN,REDACTED,REDACTED,FAA Form 5200-7-E,Pilot,11/09/23 00:00:00,0,10.0
288602,1471176,08/25/23 00:00:00,8,2023,11:22,NaN,KORD,CHICAGO O'HARE INTL ARPT,41.97960,-87.90446,...,NaN,NaN,NaN,REDACTED,REDACTED,FAA Form 5200-7-E,Carcass Found,11/09/23 00:00:00,0,0.0

In [8]:
print(bird_df.iloc[235198])

INDEX_NR                     1156816
INCIDENT_DATE      09/17/21 00:00:00
INCIDENT_MONTH                     9
INCIDENT_YEAR                   2021
TIME                           18:03
                         ...
SOURCE             FAA Form 5200-7-E
PERSON            Airport Operations
LUPDATE            10/13/21 00:00:00
TRANSFER                           0
DISTANCE                         NaN
Name: 235198, Length: 100, dtype: object

In [9]:
bird_df = bird_df.loc[bird_df['INCIDENT_YEAR']]

0